[versions]
kotlin = "2.1.21"
kover = "0.8.3"
detekt = "1.23.8"
dokka = "2.0.0"
ksp = "2.1.21-2.0.2"
maven = "0.30.0"
ktor = "3.1.3"
kotlinx-serialization = "1.8.1"

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
maven = { id = "com.vanniktech.maven.publish", version.ref = "maven" }

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
